const actionTypes = {
    SET_MOVIES: 'SET_MOVIES',
    SET_MOVIE: 'SET_MOVIE',
    SET_SELECTED_GENRES: 'SET_SELECTED_GENRES',
    SET_GENRES: 'SET_GENRES',
    SET_SELECTED_YEAR: 'SET_SELECTED_YEAR',
}
export default actionTypes;